import { expect, test } from '@playwright/test'

test('sesión demo, recorrido, navegación y reapertura', async ({ page }) => {
  await page.goto('/login')
  await page.evaluate(() => localStorage.clear())
  await page.getByRole('button', { name: 'Personal Técnico de Farmacia' }).click()
  await expect(page).toHaveURL(/\/dashboard$/)
  const tour = page.getByRole('dialog')
  await expect(tour).toContainText('Bienvenido al sistema de monitoreo de cadena de frío')
  await expect(page.locator('aside [data-tour-route="/dashboard"]')).toBeVisible()
  await tour.getByRole('button', { name: 'Siguiente' }).click()
  await expect(tour).toContainText('Alertas')
  await tour.getByRole('button', { name: 'Atrás' }).click()
  await expect(tour).toContainText('Monitoreo')
  await page.keyboard.press('Escape')
  await expect(tour).toBeHidden()
  await page.reload()
  await expect(tour).toBeHidden()
  await page.getByRole('link', { name: 'Guía de uso' }).click()
  await page.getByRole('button', { name: 'Volver a ver recorrido' }).click()
  await expect(tour).toBeVisible()
  await tour.getByRole('button', { name: 'Omitir' }).click()
  await page.locator('aside [data-tour-route="/alertas"]').click()
  await expect(page.getByRole('heading', { name: 'Gestión de alertas' })).toBeVisible()
})

test('guardas de autenticación y permisos por rol', async ({ page }) => {
  await page.goto('/usuarios')
  await expect(page).toHaveURL(/\/login$/)
  await page.getByRole('button', { name: 'Auditor (solo lectura)' }).click()
  await page.getByRole('dialog').getByRole('button', { name: 'Omitir' }).click()
  await page.goto('/auditoria')
  await expect(page.getByRole('heading', { name: 'Bitácora de auditoría' })).toBeVisible()
  await page.goto('/usuarios')
  await expect(page.getByText(/permiso/i)).toBeVisible()
  await page.goto('/checklist-bpa')
  await expect(page.getByText(/permiso/i)).toBeVisible()
})

test('alertas permiten abrir detalle contextual', async ({ page }) => {
  await page.goto('/login')
  await page.getByRole('button', { name: 'Personal Técnico de Farmacia' }).click()
  await expect(page).toHaveURL(/\/dashboard$/)
  const tour = page.getByRole('dialog')
  await expect(tour).toBeVisible()
  await tour.getByRole('button', { name: 'Omitir' }).click()
  await expect(tour).toBeHidden()
  await page.locator('aside [data-tour-route="/alertas"]').click()
  await page.getByRole('button', { name: 'Todas' }).click()
  await expect(page.getByText('Excursión crítica').first()).toBeVisible()
  await expect(page.getByText('Riesgo preventivo').first()).toBeVisible()
  await page.getByRole('button', { name: /ver cronología de atención/i }).first().click()
  await expect(page.getByRole('dialog')).toContainText(/temperatura|dispositivo/i)
})

test('privacidad obligatoria precede recorrido inicial', async ({ page }) => {
  await page.goto('/login')
  await page.evaluate(() => localStorage.clear())
  await page.getByRole('button', { name: 'Personal Técnico de Farmacia' }).click()
  await expect(page.getByRole('dialog')).toContainText('Bienvenido al sistema')
  await page.evaluate(async () => {
    const { useAuthStore } = await import('/src/application/stores/authStore.ts')
    useAuthStore.setState({ requierePrivacidad: true })
  })
  await expect(page.getByRole('dialog')).toHaveCount(1)
  await expect(page.getByRole('dialog')).toContainText(/privacidad/i)
  await page.evaluate(async () => {
    const { useAuthStore } = await import('/src/application/stores/authStore.ts')
    useAuthStore.setState({ requierePrivacidad: false })
  })
  await expect(page.getByRole('dialog')).toContainText('Bienvenido al sistema')
})

test('logout elimina acceso a ruta protegida', async ({ page }) => {
  await page.goto('/login')
  await page.getByRole('button', { name: 'Personal Técnico de Farmacia' }).click()
  await expect(page).toHaveURL(/\/dashboard$/)
  await page.getByRole('dialog').getByRole('button', { name: 'Omitir' }).click()
  await page.getByRole('button', { name: 'Cerrar sesión' }).click()
  await expect(page).toHaveURL(/\/login$/)
  await page.goto('/alertas')
  await expect(page).toHaveURL(/\/login$/)
})

test('navegación móvil abre menú y permite llegar a alertas', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/login')
  await page.getByRole('button', { name: 'Personal Técnico de Farmacia' }).click()
  await expect(page).toHaveURL(/\/dashboard$/)
  await page.getByRole('dialog').getByRole('button', { name: 'Omitir' }).click()
  await page.getByRole('button', { name: 'Abrir menú' }).click()
  await page.getByRole('dialog').getByRole('link', { name: 'Alertas' }).click()
  await expect(page.getByRole('heading', { name: 'Gestión de alertas' })).toBeVisible()
  await expect(page.getByRole('dialog')).toBeHidden()
})

test('trazabilidad explica cadena, oculta sellos y muestra verificación', async ({ page }) => {
  await page.goto('/login')
  await page.getByRole('button', { name: 'Personal Técnico de Farmacia' }).click()
  await expect(page).toHaveURL(/\/dashboard$/)
  await page.getByRole('dialog').getByRole('button', { name: 'Omitir' }).click()
  await page.goto('/trazabilidad')
  await expect(page.getByText('Registro N+1')).toBeVisible()
  await expect(page.getByRole('columnheader', { name: 'Sello anterior' })).toHaveCount(0)
  await page.getByRole('button', { name: 'Mostrar detalles técnicos de los sellos' }).click()
  await expect(page.getByRole('columnheader', { name: 'Sello anterior' })).toBeVisible()
  await page.getByRole('button', { name: 'Verificar registros' }).click()
  await expect(page.getByText(/registros intactos|alteración detectada/i).first()).toBeVisible()
})
